[tool.poetry]
name = "multigrate"
version = "1.0.0"
description = "multiomic data integration for signle-cell genomics"
authors = ["Anastasia Litinetskaya <anastasia.litinetskaya@helmholtz-muenchen.de>", "Mohammad Lotfollahi <mohammad.lotfollahi@helmholtz-muenchen.de>"]
homepage = "https://github.com/theislab/multigrate/"
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
adjustText = { version = "*", optional = true }
python = ">=3.9,<3.11"
scikit-learn = "^1.0.2"
statsmodels = "^0.13.2"
numba = "^0.55.1"
tables = "^3.7.0"
notebook = "^6.4.10"
loompy = { version = ">=3.0.6", optional = true }
nbconvert = { version = ">=5.4.0", optional = true }
nbformat = { version = ">=4.4.0", optional = true }
nbsphinx = { version = "*", optional = true }
nbsphinx-link = { version = "*", optional = true }
pre-commit = { version = ">=2.7.1", optional = true }
pydata-sphinx-theme = { version = ">=0.4.0", optional = true }
jupyter = { version = ">=1.0", optional = true }
importlib-metadata = { version = "*", optional = true }
ipython = { version = ">=7.1.1", optional = true }
leidenalg = "^0.8.9"
louvain = "^0.7.1"
torch = "^1.11.0"
scanpy = "^1.9.0"
python-igraph = { version = "*", optional = true }
scanpydoc = { version = ">=0.5", optional = true }
scikit-misc = { version = ">=0.1.3", optional = true }
scvi-tools = ">=0.14.6,<0.15.0"
sphinx = { version = ">=4.1,<4.4", optional = true }
sphinx-autodoc-typehints = { version = "*", optional = true }
sphinx-rtd-theme = { version = "*", optional = true }
typing_extensions = { version = "*", python = "<3.8" }

[tool.poetry.extras]
docs = [
    "jinja2<3.0.3",
    "scanpy",
    "sphinx",
    "scanpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "ipython",
    "pydata-sphinx-theme",
    "typing_extensions",
    "sphinx-autodoc-typehints",
    "sphinx_gallery",
    "sphinx-rtd-theme",
]
tutorials = ["scanpy", "leidenalg", "python-igraph", "loompy", "scikit-misc"]

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.masonry.api"
requires = [
    "poetry>=1.0",
    "setuptools", # keep it here or "pip install -e" would fail
]